JIRA_USER=alejandro.sanhueza@u-planner.com
JIRA_TOKEN=ATATT3xFfGF04qQDnUpJyatQHynqucNwhj6G32Qt6-gUaPlX1BITcYSPd-s14jMC2tlZQy5_wRf-2pgOpVIYw5WLirvN2iRuHEWzYghjJlCn6lmePdiBx5_1IM1nE5HDVm1ud3bs8gsXVQnidjQUHEahs4YoXToffD9Edpf24wWGmYQ2RA7zsQ0=30B76859
JIRA_SERVER=https://u-planner.atlassian.net
OPENAI_API_KEY=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
